# Generated by Django 5.1.4 on 2024-12-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathmentor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_contact', models.CharField(max_length=15)),
                ('debt_status', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('book_progress', models.CharField(blank=True, max_length=255, null=True)),
                ('last_lesson_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
