# Generated by Django 5.1.4 on 2025-06-14 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathmentor', '0003_assignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='lesson_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lesson_type', models.CharField(choices=[('online', 'Online'), ('physical', 'Yüz Yüze')], default='physical', max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Planlandı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi'), ('missed', 'Katılmadı')], default='scheduled', max_length=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Bekliyor'), ('paid', 'Ödendi'), ('overdue', 'Vadesi Geçti')], default='pending', max_length=10)),
                ('lesson_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('topic_covered', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='mathmentor.student')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='mathmentor.lesson'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('lesson_reminder', 'Ders Hatırlatması'), ('payment_reminder', 'Ödeme Hatırlatması'), ('assignment_reminder', 'Ödev Hatırlatması'), ('general', 'Genel')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('send_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mathmentor.lesson')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mathmentor.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Pazartesi'), ('tuesday', 'Salı'), ('wednesday', 'Çarşamba'), ('thursday', 'Perşembe'), ('friday', 'Cuma'), ('saturday', 'Cumartesi'), ('sunday', 'Pazar')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lesson_type', models.CharField(choices=[('online', 'Online'), ('physical', 'Yüz Yüze')], default='physical', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='mathmentor.student')),
            ],
            options={
                'unique_together': {('student', 'day_of_week', 'start_time')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mathmentor.schedule'),
        ),
    ]
