# Generated by Django 5.1.4 on 2025-06-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathmentor', '0004_alter_assignment_options_assignment_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='book_progress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
